services:
  gosimple:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    #    environment:
#      GO_ENV: production
#      JWT_SECRET: mysecretkey
#      PORT: "8080"
#      DB_HOST: db
#      DB_NAME: book-swap
#      DB_USER: postgres
#      DB_PASSWORD: 2005Wppt++
#      DB_PORT: "5432"
    depends_on:
      - db
    networks:
      - gosimple-network

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005Wppt++
      POSTGRES_DB: book-swap
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gosimple-network

networks:
  gosimple-network:
    driver: bridge

volumes:
  postgres-data:
